# This is a basic workflow to help you get started with Actions

name: Deploy Demo Site

# Controls when the action will run. 
on:
  push:
    paths:
      - 'demo/**'
    #branches: [ main ] # TODO uncomment out when merging

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    concurrency: pokegen-demo
    # The type of runner that the job will run on
    runs-on: [self-hosted,deploy]

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      API_URL: ${{ secrets.API_URL }}
      API_USERNAME: ${{ secrets.API_USERNAME }}
      API_PASSWORD: ${{ secrets.API_PASSWORD }}
      DOMAIN_URL: ${{ secrets.DOMAIN_URL }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: deploy
        run: docker-compose -f demo/docker-compose.yaml up --build -d
